version: '2'
services:
    daspanel-redis:
        image: daspanel/redis
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        env_file:
            - daspanel.env
    daspanel-redis-cli:
        image: daspanel/redis
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        env_file:
            - daspanel.env

networks:  
  backend:
    driver: bridge


